#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "HOME_AUTOMATION"
  https://create.arduino.cc/cloud/things/83a62d76-5338-4731-8b47-ac7180201a8a 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  CloudLight light;
  CloudColoredLight coloredLight;
  CloudDimmedLight dimmedLight;
  CloudTemperature temperature;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
//#include <ChainableLED.h>

//ChainableLED leds(5, 6, 3);
const byte BUTTON_PIN = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  /*
  //init colored leds
  leds.init();
  
  //set the button interrupt
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(BUTTON_PIN), handleButton, RISING);
  */
  temperature=22.0;
}

unsigned long tf = 0; 

void loop() {
  ArduinoCloud.update();
  // Your code here 
 
  unsigned long current = millis();
  if((current-tf)> 10000){

  temperature += 0.5;
    if(temperature > 30){
      temperature = 22.0;
    }
    tf = current;
  }
}


void onColoredLightChange() {
  ColoredLight colorlight = coloredLight.getValue();
  
  float h = colorlight.hue/360;
  float s = colorlight.sat/100;
  float b = colorlight.bri/200;
  
  /*
  if(colorlight.swi) {
    leds.setColorHSL(0,h,s,b);
  }else{
    leds.setColorHSL(0,h,s,0.0);
  }
  */
  
  Serial.print("Colored Light Status: ");
  Serial.println(colorlight.swi);
  Serial.print("Colored Light Color Hue: ");
  Serial.print(colorlight.hue);
  Serial.print(" Sat: ");
  Serial.print(colorlight.sat);  
  Serial.print(" Bri: ");
  Serial.print(colorlight.bri);
  Serial.println();  
}


void onDimmedLightChange() {
  DimmedLight dimlight = dimmedLight.getValue();
  
  /*
  float b = dimlight.bri/200;
  if(dimlight.swi){
    leds.setColorHSL(1,0.1,0.0,b);
  }else{
    leds.setColorHSL(1,0.1,0.0,0.0);
  }
  */
  
  Serial.print("Dimmed Light Status: ");
  Serial.println(dimlight.swi);
  Serial.print("Dimmed Light : ");  
  Serial.print(" Bri: ");
  Serial.print(dimlight.bri);
  Serial.println();    
}


void onLightChange() {
  /*
  if(light){
    leds.setColorHSL(2,0.1,0.0,1.0);
  }else{
    leds.setColorHSL(2,0.1,0.0,0.0);
  }
  */
    
  Serial.print("Light Status: ");
  Serial.println(light);
}

void handleButton() {
  light = !light;
  /*
  if(light){
    leds.setColorHSL(2,0.1,0.0,1.0);
  }else{
    leds.setColorHSL(2,0.1,0.0,0.0);
  }
  */
  
  Serial.print("Light: ");
  Serial.println(light);
  delayMicroseconds(50000);
    
}







